### ISSUE TITLE
ESXDos on 128k mode (for loading TRD) seems not to be working

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/ZXNext_MISTer#1]
We have tried using working copy of ESXDos on real Next, but spectrum reboots when used on ZXNext_Mister and NMI button is pressed.

**Comment by sorgelig** [comment]
while i will check what's wrong, there is no much point to use TRD on Next. ZX Spectrum core is much better in terms of compatibility. Also you don't need to use VHD but TRD/SCL files directly.

**Comment by sorgelig** [comment]
here is similar discussion about MiST port:
http://www.specnext.com/forum/viewtopic.php?f=6&t=1963
unfortunately i was late to grab that file so i cannot test if it fixes problem on MiSTer as well or it's something different.

I need that nextzxos-30110.zip..

**Comment by sorgelig** [comment]
already fixed
