### ISSUE TITLE
New firmware doesn’t work with current core

### ISSUE THREAD

**Issue by Swainy101** [MiSTer-devel/ZXNext_MISTer#12]
The current Spectrum Next firmware does not work with the current core and a few of the latest games will not load without this.

**Comment by malaespera** [comment]
The new AticAtac Game needs CORE 3.02.0 and NextZXOS 2.02 or above.

**Comment by Swainy101** [comment]
New Spectrum Next firmware seems to have broken this core making newer Spectrum Next games incompatible.

**Comment by albconde** [comment]
Core update to 3.02  , newest firmware 1.44.bd works , you can close this issue , all the games seen to work now
