### ISSUE TITLE
CORE VERSION 3.02.01

### ISSUE THREAD

**Issue by bymarcao** [MiSTer-devel/ZXNext_MISTer#13]
Hi guys, we're missing the new ZXNext core to run the atictac game

**Comment by cwscws** [comment]
Just noticed that too. That seems to be the only game that needs 3.02

**Comment by cwscws** [comment]
Will there be an update to the latest Core? Still waiting...

**Comment by albconde** [comment]
Core update to 3.02   , 3.02.01 is a minor fix for KS2 that not afect to mister version , you can close this issue
