### ISSUE TITLE
I have a problem with the NMI menu

### ISSUE THREAD

**Issue by micv2** [MiSTer-devel/ZXNext_MISTer#15]
Hello everyone,

I use MiST v1.5, sorry if I'm in the wrong place. When I press F9 (NMI) and want to go into the settings, I get an "error loading enMf5.sys" . Actually, I can hardly load anything in the NMI menu, I always get an "Error loading xxyy.sys". The files are on the SD card. I've tried various SD cards, to no avail. I have the latest distro 22.10a on the SD card. I've also reported the problem to Gyurco, I hope you can help me. Sometimes settings in the NMI have to be changed, and I can't get there. Maybe it's just a small thing and I can't figure it out 😟

https://github.com/mist-devel/mist-board/issues/165

Best Regards,
MiC

![IMG_4407](https://github.com/user-attachments/assets/0311243e-34a3-4b95-b01f-c74d949e7583)

**Comment by sorgelig** [comment]
You are definitely in a wrong place. This is MiSTer repository, not MiST.
